[phases.setup]
nixPkgs = ["postgresql"]

[phases.install]
cmds = [
    "gem install bundler -v 2.5.0 --no-document",
    "bundle lock --update",
    "bundle install"
]

[start]
cmd = "bundle exec puma -C config/puma.rb"
